/* The following code was generated by JFlex 1.4.1 on 11/10/11 02:30 PM */

import java.io.*;
import java.lang.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 11/10/11 02:30 PM from the specification file
 * <tt>src/flex/lexico.flex</tt>
 */
class lexico {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
    18,  0,  0,  0,  0,  0,  0, 32, 29, 30, 24, 22,  0, 23,  0, 25, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 26, 28, 27,  0, 
     0, 21,  6,  8,  3,  1,  7, 20, 17, 10,  0,  0, 15, 19,  2, 11, 
    12,  0, 13,  4,  9,  5,  0, 16, 14,  0,  0,  0,  0,  0, 31,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\21\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\5\0\1\14\11\0\1\15"+
    "\1\0\1\16\1\17\7\0\1\20\1\21\1\22\1\23"+
    "\1\24\2\0\1\25\1\26\2\0\1\27\5\0\1\30"+
    "\1\31\3\0\1\32\4\0\1\33\1\34\1\0\1\35"+
    "\1\36\12\0\1\37\1\40\1\41\10\0\1\42\2\0"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\0\1\51"+
    "\1\52\1\53\4\0\1\54\1\0\1\55\2\0\1\56";

  private static int [] zzUnpackAction() {
    int [] result = new int[130];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\41\0\102\0\143\0\204\0\245\0\306\0\347"+
    "\0\u0108\0\u0129\0\u014a\0\u016b\0\u018c\0\u01ad\0\u01ce\0\u01ef"+
    "\0\u0210\0\u0231\0\u0231\0\u0231\0\u0231\0\u0252\0\u0273\0\u0231"+
    "\0\u0231\0\u0231\0\u0231\0\u0231\0\u0294\0\u02b5\0\u02d6\0\u02f7"+
    "\0\u0318\0\u0339\0\u035a\0\u037b\0\u039c\0\u03bd\0\u03de\0\u03ff"+
    "\0\u0420\0\u0441\0\u0462\0\u0231\0\u0483\0\u0231\0\u0231\0\u04a4"+
    "\0\u04c5\0\u04e6\0\u0507\0\u0528\0\u0549\0\u056a\0\u0231\0\u0231"+
    "\0\u0231\0\u0231\0\u058b\0\u05ac\0\u05cd\0\u0231\0\u0231\0\u05ee"+
    "\0\u060f\0\u0231\0\u0630\0\u0651\0\u0672\0\u0693\0\u06b4\0\u0231"+
    "\0\u0231\0\u06d5\0\u06f6\0\u0717\0\u0231\0\u0738\0\u0759\0\u077a"+
    "\0\u079b\0\u0231\0\u0231\0\u07bc\0\u07dd\0\u0231\0\u07fe\0\u081f"+
    "\0\u0840\0\u0861\0\u0882\0\u08a3\0\u08c4\0\u08e5\0\u0906\0\u0927"+
    "\0\u0231\0\u0231\0\u0231\0\u0948\0\u0969\0\u098a\0\u09ab\0\u09cc"+
    "\0\u09ed\0\u0a0e\0\u0a2f\0\u0231\0\u0a50\0\u0a71\0\u0231\0\u0231"+
    "\0\u0231\0\u0231\0\u0231\0\u0231\0\u0a92\0\u0231\0\u0231\0\u0231"+
    "\0\u0ab3\0\u0ad4\0\u0af5\0\u0b16\0\u0231\0\u0b37\0\u0231\0\u0b58"+
    "\0\u0b79\0\u0231";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[130];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\2\1\3\1\4\1\5\1\6\1\0\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\0\1\16"+
    "\1\17\2\0\1\20\1\0\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\2\0\1\35\14\0\1\36\22\0\1\37\11\0\1\40"+
    "\37\0\1\41\1\42\26\0\1\43\3\0\1\44\3\0"+
    "\1\45\1\46\6\0\1\47\21\0\1\50\43\0\1\51"+
    "\5\0\1\52\44\0\1\53\34\0\1\54\27\0\1\55"+
    "\4\0\1\56\46\0\1\57\40\0\1\60\24\0\1\61"+
    "\52\0\1\62\26\0\1\63\17\0\1\64\32\0\1\65"+
    "\27\0\1\66\1\0\1\67\130\0\1\70\1\71\40\0"+
    "\1\72\7\0\1\73\41\0\1\74\52\0\1\75\33\0"+
    "\1\76\52\0\1\77\22\0\1\100\52\0\1\101\27\0"+
    "\1\102\47\0\1\103\25\0\1\104\63\0\1\105\24\0"+
    "\1\106\31\0\1\107\53\0\1\110\27\0\1\111\45\0"+
    "\1\112\2\0\1\113\36\0\1\114\51\0\1\115\17\0"+
    "\1\116\10\0\1\117\27\0\1\120\50\0\1\121\31\0"+
    "\1\122\40\0\1\123\57\0\1\124\17\0\1\125\50\0"+
    "\1\126\35\0\1\127\33\0\1\130\51\0\1\131\52\0"+
    "\1\132\31\0\1\133\35\0\1\134\36\0\1\135\31\0"+
    "\1\136\44\0\1\137\35\0\1\140\62\0\1\141\30\0"+
    "\1\142\27\0\1\143\54\0\1\144\33\0\1\145\40\0"+
    "\1\146\45\0\1\147\31\0\1\150\32\0\1\151\55\0"+
    "\1\152\22\0\1\153\56\0\1\154\32\0\1\155\53\0"+
    "\1\156\25\0\1\157\40\0\1\160\30\0\1\161\46\0"+
    "\1\162\40\0\1\163\32\0\1\164\50\0\1\165\53\0"+
    "\1\166\15\0\1\167\42\0\1\170\47\0\1\171\27\0"+
    "\1\172\61\0\1\173\31\0\1\174\42\0\1\175\33\0"+
    "\1\176\32\0\1\177\63\0\1\200\17\0\1\201\35\0"+
    "\1\202\37\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2970];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\21\0\4\11\2\1\5\11\5\0\1\1\11\0\1\11"+
    "\1\0\2\11\7\0\4\11\1\1\2\0\2\11\2\0"+
    "\1\11\5\0\2\11\3\0\1\11\4\0\2\11\1\0"+
    "\1\1\1\11\12\0\3\11\10\0\1\11\2\0\6\11"+
    "\1\0\3\11\4\0\1\11\1\0\1\11\2\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[130];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
	static FileInputStream FInStr = null;
	static String fInName ; //nombre archivo entrada


	public static void main (String argv[])
	throws java.io.IOException {
                argv = new String[]{"entrada.txt"};
		int numparams = argv.length; //n�mero argumentos pasados

		//Obtenci�n de par�metros pasados en l�nea de comandos
		if ( numparams != 1) 
		{ 	//error: nr. Par�metros incorrecto
			System.out.println ("N�mero par�metros incorrecto!. Uso: ");
			System.out.println ( "\tjava lexico archivo.EXT");
			return; 
		}
		else 
		{ 	fInName = argv[0];		
			lexico yy = new lexico(new FileInputStream(fInName));
			while (yy.yylex() != -1) ; 
		}

	} //Final main


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  lexico(java.io.Reader in) throws 	FileNotFoundException
 {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  lexico(java.io.InputStream in) throws 	FileNotFoundException
 {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 29: 
          { System.out.print("token ELSE\n");
          }
        case 47: break;
        case 4: 
          { System.out.print("token DIVIDE\n");
          }
        case 48: break;
        case 30: 
          { System.out.print("token NEXT\n");
          }
        case 49: break;
        case 14: 
          { System.out.print("token IF\n");
          }
        case 50: break;
        case 45: 
          { System.out.print("token FUNC\n");
          }
        case 51: break;
        case 10: 
          { System.out.print("token CIRCUN\n");
          }
        case 52: break;
        case 43: 
          { System.out.print("token SHA\n");
          }
        case 53: break;
        case 3: 
          { System.out.print("token MULTIPLICA\n");
          }
        case 54: break;
        case 22: 
          { System.out.print("token DIM\n");
          }
        case 55: break;
        case 7: 
          { System.out.print("token IGUAL\n");
          }
        case 56: break;
        case 44: 
          { System.out.print("token INT\n");
          }
        case 57: break;
        case 25: 
          { System.out.print("token CLS\n");
          }
        case 58: break;
        case 38: 
          { System.out.print("token END IF\n");
          }
        case 59: break;
        case 19: 
          { System.out.print("token MAYORI\n");
          }
        case 60: break;
        case 39: 
          { System.out.print("token ELSIF\n");
          }
        case 61: break;
        case 27: 
          { System.out.print("token MOD\n");
          }
        case 62: break;
        case 31: 
          { System.out.print("token LONG\n");
          }
        case 63: break;
        case 26: 
          { System.out.print("token REM\n");
          }
        case 64: break;
        case 15: 
          { System.out.print("token OR\n");
          }
        case 65: break;
        case 28: 
          { System.out.print("token AND\n");
          }
        case 66: break;
        case 40: 
          { System.out.print("token DOU\n");
          }
        case 67: break;
        case 18: 
          { System.out.print("token MENORI\n");
          }
        case 68: break;
        case 46: 
          { System.out.print("token SELC\n");
          }
        case 69: break;
        case 2: 
          { System.out.print("token RESTA\n");
          }
        case 70: break;
        case 36: 
          { System.out.print("token PRINT\n");
          }
        case 71: break;
        case 8: 
          { System.out.print("token PARENA\n");
          }
        case 72: break;
        case 21: 
          { System.out.print("token NOT\n");
          }
        case 73: break;
        case 34: 
          { System.out.print("token UNTIL\n");
          }
        case 74: break;
        case 9: 
          { System.out.print("token PARENC\n");
          }
        case 75: break;
        case 1: 
          { System.out.print("token SUMA\n");
          }
        case 76: break;
        case 20: 
          { System.out.print("token END\n");
          }
        case 77: break;
        case 33: 
          { System.out.print("token WEND\n");
          }
        case 78: break;
        case 23: 
          { System.out.print("token SUB\n");
          }
        case 79: break;
        case 12: 
          { System.out.print("token DO\n");
          }
        case 80: break;
        case 13: 
          { System.out.print("token TO\n");
          }
        case 81: break;
        case 5: 
          { System.out.print("token MENOR\n");
          }
        case 82: break;
        case 16: 
          { System.out.print("token AS\n");
          }
        case 83: break;
        case 11: 
          { System.out.print("token COMILLA\n");
          }
        case 84: break;
        case 17: 
          { System.out.print("token DIFERENTE\n");
          }
        case 85: break;
        case 42: 
          { System.out.print("token SIN\n");
          }
        case 86: break;
        case 6: 
          { System.out.print("token MAYOR\n");
          }
        case 87: break;
        case 24: 
          { System.out.print("token FOR\n");
          }
        case 88: break;
        case 32: 
          { System.out.print("token LOOP\n");
          }
        case 89: break;
        case 41: 
          { System.out.print("token STR\n");
          }
        case 90: break;
        case 35: 
          { System.out.print("token INPUT\n");
          }
        case 91: break;
        case 37: 
          { System.out.print("token WHILE\n");
          }
        case 92: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return YYEOF;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
