
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 13 08:17:54 GMT-04:30 2011
//----------------------------------------------------

package flex;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTE = 36;
  public static final int OVER = 42;
  public static final int INPUT = 14;
  public static final int SEMI = 45;
  public static final int LPAREN = 43;
  public static final int INT = 25;
  public static final int MINUS = 40;
  public static final int FOR = 15;
  public static final int CS = 38;
  public static final int RPAREN = 44;
  public static final int NOT = 32;
  public static final int AND = 30;
  public static final int LT = 33;
  public static final int FL = 47;
  public static final int OR = 31;
  public static final int RT = 34;
  public static final int RTE = 35;
  public static final int UNTIL = 6;
  public static final int NUM = 10;
  public static final int PLUS = 39;
  public static final int NEXT = 16;
  public static final int LOOP = 21;
  public static final int ASSIGN = 46;
  public static final int IF = 2;
  public static final int DOU = 29;
  public static final int ID = 7;
  public static final int DIM = 24;
  public static final int EOF = 0;
  public static final int COMILLAS = 9;
  public static final int error = 1;
  public static final int COMA = 51;
  public static final int CIR = 53;
  public static final int WEND = 19;
  public static final int DIF = 37;
  public static final int CLS = 17;
  public static final int MOD = 52;
  public static final int COM = 50;
  public static final int TIMES = 41;
  public static final int ENDIF = 20;
  public static final int ELSE = 4;
  public static final int FUNC = 12;
  public static final int TO = 49;
  public static final int WHILE = 18;
  public static final int THEN = 3;
  public static final int ID2 = 8;
  public static final int COMEN = 23;
  public static final int END = 5;
  public static final int LONG = 28;
  public static final int STRING = 27;
  public static final int AS = 26;
  public static final int SUB = 11;
  public static final int PRINT = 13;
  public static final int DO = 22;
  public static final int STEP = 48;
}

