
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Oct 15 20:08:36 GMT-04:30 2011
//----------------------------------------------------

package flex;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTE = 37;
  public static final int OVER = 43;
  public static final int INPUT = 14;
  public static final int SEMI = 46;
  public static final int LPAREN = 44;
  public static final int DOUN = 56;
  public static final int NUMP = 8;
  public static final int INT = 25;
  public static final int MINUS = 41;
  public static final int FOR = 15;
  public static final int CS = 39;
  public static final int RPAREN = 45;
  public static final int NOT = 33;
  public static final int AND = 31;
  public static final int ELSEIF = 55;
  public static final int LT = 34;
  public static final int FL = 48;
  public static final int RT = 35;
  public static final int OR = 32;
  public static final int RTE = 36;
  public static final int UNTIL = 6;
  public static final int NUM = 10;
  public static final int PLUS = 40;
  public static final int NEXT = 16;
  public static final int LOOP = 21;
  public static final int ASSIGN = 47;
  public static final int IF = 2;
  public static final int DOU = 30;
  public static final int ID = 7;
  public static final int DIM = 24;
  public static final int EOF = 0;
  public static final int ASS = 27;
  public static final int COMILLAS = 9;
  public static final int error = 1;
  public static final int COMA = 52;
  public static final int CIR = 54;
  public static final int WEND = 19;
  public static final int DIF = 38;
  public static final int CLS = 17;
  public static final int MOD = 53;
  public static final int ASI = 26;
  public static final int COM = 51;
  public static final int TIMES = 42;
  public static final int ASD = 28;
  public static final int ENDIF = 20;
  public static final int ELSE = 4;
  public static final int FUNC = 12;
  public static final int TO = 50;
  public static final int WHILE = 18;
  public static final int THEN = 3;
  public static final int COMEN = 23;
  public static final int END = 5;
  public static final int STRING = 29;
  public static final int STRD = 57;
  public static final int SUB = 11;
  public static final int PRINT = 13;
  public static final int DO = 22;
  public static final int STEP = 49;
}

